      <div class="leg-footer d-print-none">
        <footer class="footer bg-light">
          <div class="container" style="">
            <div class="row pt-3 px-4">            
              <div class="col-sm">
                <h4 class="title-widget text-left">About the Legislature</h4>
                <ul  class="list-unstyled clear-margins">
                  <li>
                    <a href="http://www.leg.state.mn.us/lrl/history/">Historical Information</a>
                  </li>
                  <li>
                    <a href="http://www.leg.state.mn.us/leg/jobs.aspx">Employment/Internships</a>
                  </li>
                  <li>
                    <a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx?subject=14">Visiting the Capitol</a>
                  </li>

                  <li>
                    <a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx?id=98">Accessibility</a>
                  </li>
                  <li>
                    <a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx">FAQ</a>
                  </li>
                </ul>
              </div>
              <div class="col-sm">
                <h4 class="title-widget text-left">Contact Your Legislator</h4>
                <ul  class="list-unstyled clear-margins">
                  <li   class="mt-2"><a href="http://www.gis.leg.mn/OpenLayers/districts/">Who Represents Me?</a></li>
                  <li><a href="http://www.house.leg.state.mn.us/members/hmem.asp">House Members</a></li>
                  <li><a href="http://www.senate.leg.state.mn.us/members/index.php">Senators</a></li>
                </ul>
              </div>
              <div class="col-sm">
                <h4 class="title-widget text-left">General Contact</h4>
                <ul  class="list-unstyled clear-margins">
                  <li  class="mt-2">Contact a legislative librarian:</li>
                  <li><a href="tel:651-296-8338">(651) 296-8338</a> or <a href="http://www.leg.state.mn.us/leg/comments.aspx">Email</a></li>

                  <li  class="mt-2"><a href="http://www.leg.state.mn.us/leg/legdir.aspx">Phone Numbers</a></li>         
                  <li><a href="http://www.leg.state.mn.us/leg/comments.aspx">Submit website comments</a></li>            
                </ul>
              </div>
              <div class="col-sm">
                <h4 class="title-widget">Get Connected</h4>
                <ul class="list-unstyled clear-margins">
                  <li><a href="http://www.house.mn/hinfo/news.asp">House News</a></li>
                  <li><a href="http://www.senate.leg.state.mn.us/media/">Senate News</a></li>
                  <li><a href="http://www.leg.state.mn.us/mybills/">MyBills</a></li>
                  <li><a href="http://www.leg.state.mn.us/leg/elists.aspx">Email Updates &amp; RSS Feeds</a></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>
        <div class="row">
          <div class="col-12 bg-dark">
            <div class="text-center text-light py-1 leg-subfooter">Minnesota House of Representatives · 100 Rev. Dr. Martin Luther King Jr. Blvd. Saint Paul, MN 55155 · <a href="mailto:Webmaster@house.mn">Webmaster@house.mn</a></div>
          </div>
        </div>
      </div>
    </div> <!-- container.fluid (from top) -->
    <script src="https://ww2.gis.leg.mn/iMaps/bootstrap4/js/jquery-ui-1.12.1.custom/jquery-ui.min.js">
    </script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js">
    </script> 
    <script src="https://ww2.gis.leg.mn/iMaps/bootstrap4/node_modules/bootstrap/dist/js/bootstrap.min.js">
    </script> 
  </body>
</html>